name: VPN Connect Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Typical Usage of OpenVPN
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "./"
        with:
          config_file: .github/workflows/client.ovpn
      - name: Check if connected
        run: curl -v ${{ secrets.TARGET_URL }}
